### ISSUE TITLE
DB PK (Brand) violation at /Acceptances/EnterProducts

### ISSUE THREAD

**Issue by PhilMuehlberger** [braunau-mobil/velo-basar#77]
Happens when adding new articles and hitting "Annahmebeleg drucken"

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 23505: duplicate key value violates unique constraint "PK_Brand"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 490
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1215
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken) in C:\projects\npgsql-entityframeworkcore-postgresql\src\EFCore.PG\Storage\Internal\NpgsqlExecutionStrategy.cs:line 49
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at BraunauMobil.VeloBasar.Data.VeloBasarContext.InsertProductsAsync(IList`1 products) in /home/pmuehlberger/WORK/braunaumobil/BASAR/velo-basar/src/BraunauMobil.VeloBasar/Data/VeloBasarContext.cs:line 501
   at BraunauMobil.VeloBasar.Data.VeloBasarContext.AcceptProductsAsync(Basar basar, Int32 sellerId, PrintSettings printSettings, IList`1 products) in /home/pmuehlberger/WORK/braunaumobil/BASAR/velo-basar/src/BraunauMobil.VeloBasar/Data/VeloBasarContext.cs:line 48
   at BraunauMobil.VeloBasar.Pages.Acceptances.AcceptModel.OnGetAsync(AcceptParameter parameter) in /home/pmuehlberger/WORK/braunaumobil/BASAR/velo-basar/src/BraunauMobil.VeloBasar/Pages/Acceptances/Accept.cshtml.cs:line 24
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)



.AspNet.Consent | yes
-- | --
.AspNetCore.Antiforgery.O7SDS4L1wtM | CfDJ8CQAce8VIcJEgaDcP6jy9QfdWlAswSIT44DssWUIhftlYuEz-hSrwKiHKUYesUZk4Q0To1mKerrqexSxOZQZsEQDnG3pajM1ms6elQJ-oD-Cog0bLpp5I4pv4X33Mt3cwBiRSJdOE2czoiNPEAyuZwM
.AspNetCore.Identity.Application | CfDJ8CQAce8VIcJEgaDcP6jy9QcIqGCBZbO-DWrHrAXvs0Nw7jAnXm0uO9mValmj2U4eD_ZqRlhS63PIMePJwitexHAvTK_0DZsVCXm_mtSfQX75YcNb7d8457ysNq9mI9oz3etUZps65fO9SCIPs7intZXAvPd9qA7r5DGrr014ZD4mlYODFiMffY-HnuMr8vF-UeuWiBG9eZTPXoqEwzX5-AAHEP3n1yqYoqqrrX1-eZXJE80awTk1LiNLNk502AtS-_oMXowB1VeoCU3XcwtfPxDIU8KKqwQzDGOyUEOLwNlFnXXIgkAryXIYU5pa6MrpnTZPrF9hD3hthbBM-IAyK6lFR_tXJLeoxH1Ecw8Rm-MEu3MX3P6lu3FLVHihgJ7q5yvFv2_1Ka2RKa0fWaPtN5XQqxG0x6zJIFVE1bm6sr1OAWj4Af_o0AhUtPS8wyo9zYzmxee9xbWps0iewOOjTzvjdAkCAe65bCy1SXGwu9V6-x5xeQ_gIHUn4BugBZwkqYwDKR-kkobf7_3wqjb1_xC91WD3p_O_o4CIgUI9EfDHHYwsa4jqC1zwbwqanH3B4_8cxZIk192iVvyq8yac83hV-9yuh6AHBGj6CFqykJ44GVxw7k0pZZiypaeDvb6XrQ
acceptanceProducts | [{"Id":0,"FrameNumber":"43573485","Color":"weiss orange","BrandId":1,"Brand":{"Id":1,"Name":"Tern","State":0},"Description":"Verge X10","TypeId":1,"Type":{"Id":1,"Name":"Klapprad","State":0},"TireSize":"ERTRO 406","Price":400.0,"StorageState":0,"ValueState":0,"Label":null}]
wordpress_test_cookie | WP+Cookie+check
wp-settings-time-1 | 1573418364
```

**Comment by PhilMuehlberger** [comment]
Culprit:
https://github.com/braunau-mobil/velo-basar/blob/master/src/BraunauMobil.VeloBasar/Data/VeloBasarContext.cs#L485

These two if's cause the PK violation. Can they be removed? Insert without existing brand/type does not seem to be possible anyway. Not sure right now. Checking.

**Comment by Spacelord-XaN** [comment]
Finally found the real issue:
If ef core data objects are serialized to JSON and deserialized, the tracker does not know about them, thus thinking these are new objects and should be created on insert.

Added reloading the relations of the products after deserializing them from cookies.

**Comment by Spacelord-XaN** [comment]
Try the Attach method

**Comment by Spacelord-XaN** [comment]
Attach does the job better!
