### ISSUE TITLE
Exception when show Seller Details when seller has successfull acceptance items

### ISSUE THREAD

**Issue by PhilMuehlberger** [braunau-mobil/velo-basar#79]
URL https://localhost:5001/Sellers/Details?SellerId=1
after two articles have been added for seller

```
Show raw exception details
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at BraunauMobil.VeloBasar.Pages.Sellers.DetailsModel.GetDocumentPage(ProductsTransaction transaction) in /home/pmuehlberger/WORK/braunaumobil/BASAR/velo-basar/src/BraunauMobil.VeloBasar/Pages/Sellers/Details.cshtml.cs:line 49
   at BraunauMobil.VeloBasar.Pages.Sellers.Pages_Sellers_Details.<ExecuteAsync>b__17_24() in /home/pmuehlberger/WORK/braunaumobil/BASAR/velo-basar/src/BraunauMobil.VeloBasar/Pages/Sellers/Details.cshtml:line 104
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at BraunauMobil.VeloBasar.Pages.Sellers.Pages_Sellers_Details.ExecuteAsync() in /home/pmuehlberger/WORK/braunaumobil/BASAR/velo-basar/src/BraunauMobil.VeloBasar/Pages/Sellers/Details.cshtml:line 81
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by PhilMuehlberger** [comment]
Suppose this is only a consequence of not being able to create acceptance PDF (which failed for another exception). Maybe irrelevant. Need to research PDF creation.

**Comment by Spacelord-XaN** [comment]
fixed
